### ISSUE TITLE
ionic 3 with this plugin build error

### ISSUE THREAD

**Issue by Avishaidev** [ahkohd/ngx-emoji-picker#1]
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by ahkohd** [comment]
> ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
> Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Am sorry for the late reply. I mistakenly imported BrowserModule instead of Using the CommonModule. I have fixed this issue. All you have to do is to update the package to the latest version.
```bash
$npm i ngx-emoji-picker@0.0.2 --save
```
