### ISSUE TITLE
Style of the emoji's

### ISSUE THREAD

**Issue by candorthor** [ahkohd/ngx-emoji-picker#12]
Hi @ahkohd 

I am using this plugin. And I wanted to change the style of the emoji's 

How my emoji's look
![image](https://user-images.githubusercontent.com/49184671/65236969-50453180-daf7-11e9-86c2-0ae1e31b2044.png)

I need the emoji's to look like  below
![image](https://user-images.githubusercontent.com/49184671/65237089-897da180-daf7-11e9-8c8b-9746197fef63.png)

And also I wanted to place emoji content to the bottom right 
And I wanted to increase the width of the emoji content
(Screenshot attached)
![image](https://user-images.githubusercontent.com/49184671/65238890-605f1000-dafb-11e9-806c-e341ec5e628e.png)

Could you please help me in this.

**Comment by ahkohd** [comment]
Thanks for reaching out, this library uses Unicode for it emoji instead of sprites for faster loading so as a result of this, the emoji style depends on the ones specified by your hardware/os manufacturer i.e On apple devices it uses Apple's default emoji, On android, it uses Android default emoji and so on...

**Comment by candorthor** [comment]
@ahkohd 

Thank you, this is the awesome plugin.

How can I increase the width of the emoji content and place it to the bottom right as I have shown in the above screenshot

**Comment by ahkohd** [comment]
@candorthor  You can try the other angular emoji ([ngx-emoj](https://www.npmjs.com/package/ngx-emoj)) library I wrote which is customizable, themeable and has a visual  customizer [https://ahkohd.github.io/ngx-emoj/](https://ahkohd.github.io/ngx-emoj/)

**Comment by candorthor** [comment]
@candorthor 

I want ngx-emoji to load on a click.
i.e I have a button and if I click on the button that emoji content should display like I have shown in the screenshot

**Comment by candorthor** [comment]
@ahkohd 

I want ngx-emoji to load on a click.
i.e I have a button and if I click on the button that emoji content should display like I have shown in the screenshot

**Comment by ahkohd** [comment]
> @candorthor
> 
> I want ngx-emoji to load on a click.
> i.e I have a button and if I click on the button that emoji content should display as I have shown in the screenshot

Yeah, I intentionally designed **ngx-emoji** so that it gives developers the flexibility to implement how they want to make the picker visible.

You have to do this yourself, on click of a button you can reveal **ngx-emoj**

**Comment by candorthor** [comment]
@ahkohd 

In ngx-emoji-picker we had
(click)="toggled = !toggled"
[(emojiPickerIf)]="toggled"

How can it be done in ngx-emoj? Could you pleas tell.

**Comment by ahkohd** [comment]
@candorthor  I have just made an example for you on [Code SandBox](https://codesandbox.io/s/angular-xspk2), I hope you find it helpful. Here is a live demo link (https://codesandbox.io/s/angular-xspk2)[https://codesandbox.io/s/angular-xspk2]

Of course, this is a simple example and you can extend it i.e with animations or other stuff to make it more awesome.

**Comment by candorthor** [comment]
@ahkohd 

Thanks a lot Victor. This is the plugin what I wanted. It worked as I expected.

**Comment by ahkohd** [comment]
Am glad you found it helpful. Have a nice day.
