### ISSUE TITLE
export 'Renderer' was not found in '@angular/core'

### ISSUE THREAD

**Issue by clampinou** [ahkohd/ngx-emoji-picker#17]
Hey,

I'm using your cool package, but when I migrated on Angular 9, I had this error : 
`export 'Renderer' was not found in '@angular/core'
`

Is it possible to migrate to Renderer2 ? 
https://angular.io/guide/migration-renderer

Regards,
Clément

**Comment by ahkohd** [comment]
Hi, @clampinou
Thanks for reporting this, I'll patch it tonight

**Comment by ahkohd** [comment]
@clampinou I have upgraded the project to **Angular 9** and from **Renderer** to **Renderer2**. The update is now available on **NPM**: 

```bash
npm i ngx-emoji-picker@0.3.1
```
A little favour, I need you to test it, and do a prod build in your project, just to be double sure. I have done my own test here. Expecting your feedback, thanks!
