### ISSUE TITLE
It shows undefined when type emoji first. Also some emojis are showing as cube on google chrome.

### ISSUE THREAD

**Issue by crazycodewriter** [ahkohd/ngx-emoji-picker#3]
![emoji-issue](https://user-images.githubusercontent.com/45752354/58379559-3f0b6e80-7fb6-11e9-9d0d-805d73383550.png)

Some emojis are showing as cubes on Google Chrome? What's the problem? How can be it fixed? And if can't then is there way just remove these cubes from the list? Also when select emoji without any text it shows undefined text before it.
![60895960_186707698901877_5701267840728825856_n](https://user-images.githubusercontent.com/45752354/58380159-daa0dd00-7fbe-11e9-8540-ad773de6ed2e.jpg)

I used the same code which you recommended from the last issue.

**Comment by ahkohd** [comment]
To fix the undefined just make sure when you declare your ``message`` you set it to an empty string.
```ts
message: string = '';
```

**Comment by ahkohd** [comment]
Well, for those emojis that shows [], this is as a result of the package just rely on the use of HTML smiley emoji codes which  most vendors have different specification/code be it hex/dec, therefore an unknow code shows a box.

**Comment by ahkohd** [comment]
There is no direct way to fix it. But will state some possible ways.
1. You can find and use another emoji packages that uses sprites instead of char codes.
2. On pick of an emoji, you can  write a code to check if it is a [], it so it should not append it to your ``message`` string.
