### ISSUE TITLE
TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by shivamssh** [ahkohd/ngx-emoji-picker#43]
Hi ,
I am using angular 7+ but when I install ngx-emoji-picker it throws Error: "TS1086: An accessor cannot be declared in an ambient context", I found a solution that I need to upgrade but I wanted to do without that is this possible, please let me know Thanks.

**Comment by ahkohd** [comment]
Hi, @shivamssh thanks for reporting this.
For angular 7 downwards, I would suggest you use the older version.

```
npm i ngx-emoji-picker@0.0.2
```

**Comment by shivamssh** [comment]
Hi @ahkohd It worked. Thanks :)

**Comment by ahkohd** [comment]
@shivamssh Thanks, I'll update the docs.

**Comment by ahkohd** [comment]
@all-contributors please add @ahkohd  for maintaining the project.
