### ISSUE TITLE
Picker closes when clicking search field

### ISSUE THREAD

**Issue by xDuck** [ahkohd/ngx-emoji-picker#45]
Working on integrating this into a project I am working on and I can't use the search field, anytime I click on it the picker closes. Is there a fix for this? Same goes for clicking on any of the category icons at the top.

Angular9 / latest emoji picker

**Comment by ahkohd** [comment]
Hi, @xDuck thanks for reporting this. I will fix this as soon as possible.

**Comment by ahkohd** [comment]
It's been a while and there is no response, I'll close this issue.
