### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by jpike88** [ahkohd/ngx-emoji-picker#71]
css dark mode support is missing

**Comment by ahkohd** [comment]
Hi, @jpike88 ~I'll add this feature and push a new update in no time.~ 

After further consideration, I have come to the conclusion that there is no need to support dark mode out of the box.
You could easily style the picker to change its appearance for dark mode.

If you're not sure of how to go about this, let me know, I create an example for you.

Perhaps, If you're looking for more customization options you can try out [ngx-emoj](https://ahkohd.github.io/ngx-emoj/).

Thanks
