### ISSUE TITLE
When selecting an Emoji it triggers Angular Forms submit event

### ISSUE THREAD

**Issue by sudarshanadayananda** [ahkohd/ngx-emoji-picker#74]
When I using this package inside `FormGroup` once I select emoji from emoji picker in triggers forms `ngSubmit` event.

Check this Stackblitz demo.

[Stackblitz Demo](https://stackblitz.com/edit/ngx-emoji-picker-demo-p3lasx?file=src%2Fapp%2Fapp.component.html)

**Comment by elquintodev** [comment]
Is this already fixed? I am experiencing the same issue.

**Comment by elabda3company** [comment]
is there any fix for this issue ? @ahkohd
